# Generated by Django 2.2.10 on 2020-04-10 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('firstName', models.CharField(default='', max_length=20)),
                ('lastName', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='@', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stranica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=200)),
                ('staroStanje', models.TextField(default='nista')),
                ('posljedniMejl', models.DateTimeField(null=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnik.Korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='Obavjestenje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('sadrzaj', models.CharField(max_length=100)),
                ('datum', models.DateTimeField(null=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnik.Korisnik')),
            ],
        ),
    ]
