# Generated by Django 2.2.10 on 2020-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obavjestenje',
            name='datum',
            field=models.DateTimeField(null=True),
        ),
    ]
