# Generated by Django 2.2.10 on 2020-04-11 10:43

from django.db import migrations, models
import korisnik.models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stranica',
            name='posljedniMejl',
            field=models.DateTimeField(default=korisnik.models.default_start_time),
        ),
    ]
