# Generated by Django 3.0.3 on 2020-03-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='email',
            field=models.CharField(default='@', max_length=30),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='firstName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='lastName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
