# Generated by Django 2.2.10 on 2020-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnik', '0002_auto_20200409_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stranica',
            name='posljedniMejl',
            field=models.DateTimeField(null=True),
        ),
    ]
